### ISSUE TITLE
新装备新锦囊

### ISSUE THREAD

**Issue by Leucothea** [BeginnerSlob/TouhouTripleSha#104]
- [x] 核制御棒 草花3
- [x] AI
攻击范围3
当你使用【杀】指定一名角色为目标后，你可以令该角色的非锁定技无效，直到当前回合结束。

- [x] 伊吹瓢 黑桃1
- [x] AI
每当你需要使用或打出一张【闪】时，你可以弃置一张手牌，若如此做，你摸一张牌。若你以此法弃置了一张黑桃牌，视为你使用或打出了一张【闪】。

- [x] 一寸神妙碗 草花5
-1坐骑

- [x] 道忌宣谕 黑桃3/方片J
- [x] AI
出牌阶段，若你除此牌外有其他牌，对你与其距离为1的一名角色使用。你交给目标角色一张牌，然后令其将两张牌交给另一名由你指定的其他角色。

- [x] 贤石点金 红桃J
- [x] AI
出牌阶段，对一名角色使用。目标角色摸三张牌，然后选择一项：弃置一张非基本牌；或弃置两张牌。

- [x] 木隐妖岚 黑桃J/红桃3
- [x] AI
出牌阶段，对一名装备区里有非宝物牌的其他角色使用。你选择一项：弃置目标角色装备区中所有的武器牌和-1坐骑牌；或弃置目标角色装备区中所有的防具牌和+1坐骑牌。

**Comment by BeginnerSlob** [comment]
伊吹瓢

**Comment by Leucothea** [comment]
"此法弃置了一张黑桃牌"...
