### ISSUE TITLE
断线重连还是有问题，照Para的merge后就有问题了 - -果然还是只能传int

### ISSUE THREAD

**Issue by BeginnerSlob** [BeginnerSlob/TouhouTripleSha#11]
具体是指断线重连后性别没有正确显示的问题。

**Comment by YanGuam** [comment]
Q_ENUMS(General::Gender)
用以上在元对象系统中声明此枚举常量才行。。

**Comment by BeginnerSlob** [comment]
soga。。我回去改了。

**Comment by BeginnerSlob** [comment]
。。。改了还是不行，
![image](https://cloud.githubusercontent.com/assets/1858088/5694485/54841396-9999-11e4-9ade-09e987390f49.png)

**Comment by BeginnerSlob** [comment]
![image](https://cloud.githubusercontent.com/assets/1858088/5694488/8232bd56-9999-11e4-8948-cb490e31b453.png)
上面的是正常同步了性别的，
下面是重连后的显示的，也就是意味着同步失败了
![image](https://cloud.githubusercontent.com/assets/1858088/5694490/99c22d30-9999-11e4-8f85-4ff6011e9ebf.png)

**Comment by YanGuam** [comment]
在General这个类里加。。。

**Comment by BeginnerSlob** [comment]
默认就加了的有Q_ENUMS(Gender)还是说必须要加上General::???

**Comment by YanGuam** [comment]
Q_ENUMS(Gender)   在General类里

**Comment by BeginnerSlob** [comment]
有的。但是没用。

**Comment by YanGuam** [comment]
请允许我做一个悲伤的表情

**Comment by BeginnerSlob** [comment]
所以这个issue还是close了吧。。
