### ISSUE TITLE
其他要改的东西

### ISSUE THREAD

**Issue by Leucothea** [BeginnerSlob/TouhouTripleSha#14]
- [x]
剧情一览 ==> 模式一览

暗将&国战
**************
KOF
杀上保下
虎牢
**************
夫妻协战
舰娘
**************
春雪

大概这样
最上边 国战
然后特殊模式
然后场景模式
然后剧情模式

中间如果有分割线就更好了

====================

- [x] 
人物一览里面加个编号，在卡牌具体信息那边

====================

- [x] 
作为反贼时，前1个角色选项一定是东方角色。
作为忠臣内奸时，前2个角色选项一定是东方角色。
由3个下调。

====================

- [ ] 
标记下标 娃娃体 加粗加大 去掉白底

====================

- [ ] 
自定义小型场景 

====================

- [x] 
防具动画(那个盾)调小到75%左右吧
铁索的动画不要忘记左移和调小  左移三分之一个头像框宽度 调小75%左右
爱心的动画不要忘记删

====================

- [x] 
锦囊无效的动画，不要配音嗯，弄的和人物框匹配一些

====================

- [x] 
觉醒技的动画修改嗯 稍微加大一丢丢

====================

- [x] 
瑞凤的剧情 崎往  音效时机改为 "效果持续中，则出牌阶段开始时" 播音效

====================

- [x] 
春雪异变中的 "再迷归·春醉" 里面的台词
能不能弄成场上谁存活，播谁的音效。。 比如4个反 死了小爱和黑白，那就只播咲夜和红白的台词 这样的。

====================

- [x] 
在主界面"人物一览" 里面 每个卡牌的三栏  设计 配音 插画 再加一览"代码" 之类的 然后都填你的名字吧 然后设计者那个 code by slob 就删掉了 整齐一点。。。

====================

- [ ] 
在主界面"卡牌一览" 里面 最右下角的音效。。。 把空属性音效去掉啦。。 然后就留 音效“按钮就好”

另外 按那个按钮 能不能顺序播放这个牌的所有音效？   现在是"杀"不管怎么按都只有"杀一下"。。。

====================

- [x] 
所有游戏牌的 游戏牌一览里面  第二行 加一句
插画：XXXXX
具体的列表我晚些给你

====================

- [ ] 
删掉主界面右下的 Qsanguosha

====================

- [ ] 
闪电的绘师 换成了 "紀奈" 这个
这里有 游戏牌的绘师 所有装备牌的绘师 写 “寒极”  就好了

**Comment by BeginnerSlob** [comment]
下次有新东西最好新开issue，不要总在一个issue里面编辑，一个issue写这么多东西很不友好。
你这里每个分隔符都应该新开个issue的

**Comment by Leucothea** [comment]
人家错啦 QAQ

**Comment by longaotianyisi** [comment]
这段对话……
