### ISSUE TITLE
两个框叠在了一起

### ISSUE THREAD

**Issue by Misaka2623** [BeginnerSlob/TouhouTripleSha#140]
心网密葬、妙手探云、荒波暴流（未测试其他牌）在需要选择目标的手牌/装备牌/判定区里的牌时，选择框的后面还会有一个框，后面的框内没有任何东西（顶部写着“谜之声”）

**Comment by BeginnerSlob** [comment]
重现没问题，但是找不到问题在哪。。需要debug小队
