### ISSUE TITLE
罔两空界 - 武将另一半不虚化

### ISSUE THREAD

**Issue by Misaka2623** [BeginnerSlob/TouhouTripleSha#141]
罔两空界的目标只有本体角色虚化，小五、神天子之类的另外一个头像不虚化

**Comment by BeginnerSlob** [comment]
这个不修了，因为化身的动画可能是新生成的，一旦新生成化身动画，新的动画item会覆盖原来的，GG

**Comment by Leucothea** [comment]
可以考虑改为，一旦中了罔两空界，就不播放左慈/小五/神天子的化身动画。
反正罔两空界也持续不了多久。
