### ISSUE TITLE
虎牢关暂时未修的问题

### ISSUE THREAD

**Issue by Leoongithub** [BeginnerSlob/TouhouTripleSha#15]
然后该角色重新进入游戏，“且该轮不能行动”（没有实现）；
虎牢关模式下所有的限定技都不能发动；
宝锤发动的回合被魔王插入回合，牌不能回到针妙丸手中。

**Comment by BeginnerSlob** [comment]
第一个没打算动

**Comment by BeginnerSlob** [comment]
第三个不是BUG

**Comment by longaotianyisi** [comment]
小人的回收时机要改一下吗？因为对被乐用技能牌收不回的事经常发生。如果这是设计者的本意请无视
