### ISSUE TITLE
标记名改动

### ISSUE THREAD

**Issue by Leucothea** [BeginnerSlob/TouhouTripleSha#151]
图都已经推了，希望把以下标记名修改...

- [ ] 绽==>咲
- [ ] 渠==>枢
- [ ] 驰==>葬
- [ ] 守==>渊
- [ ] 静==>界
- [ ] 瞬==>亟
- [ ] 缲==>徨
- [ ] 宸==>罗
- [ ] 魅==>傩
- [ ] 瞻==>恪
- [ ] 时==>倏
- [ ] 思==>略
- [ ] 谫==>哗

**Comment by BeginnerSlob** [comment]
你直接上lang里面改吧- -

**Comment by BeginnerSlob** [comment]
程序里我不打算改了

**Comment by Leoongithub** [comment]
@BeginnerSlob lang和wiki改过了，你改一下读音吧

**Comment by BeginnerSlob** [comment]
@Leoongithub 懒得改读音

**Comment by Leucothea** [comment]
这个issue要不要闭掉？
