### ISSUE TITLE
关于头像

### ISSUE THREAD

**Issue by Leucothea** [BeginnerSlob/TouhouTripleSha#155]
希望能 头像只能选择游戏内的规定的image头像

不能通过一些取巧的办法(比如增加一个别的文件，选择这个为头像，其他玩家则会显示为空)

希望能禁止此类行为

- 如果不行，就改成，如果头像是空，就让其他玩家显示电脑的头像 就是新推的story004

**Comment by longaotianyisi** [comment]
非法的头像将变为kaze001，但玩家依然可通过添加lua武将的方式来自定义头像
而其他玩家将显示该类头像为电脑头像story004
