### ISSUE TITLE
虫娘需要修改的东西(备忘)

### ISSUE THREAD

**Issue by Leucothea** [BeginnerSlob/TouhouTripleSha#161]
- [ ] 花色无论图像文字 全部统一成文字
另外 红花色文字颜色太亮 建议调暗 建议颜色#e22143

- [ ] 各种询问 或者 谜之音 字体 从华康娃娃体 改成别的字体
背景框改成选择界面的黑框， 字体改成选择界面的标题字体

**Comment by BeginnerSlob** [comment]
这里哪个改起来都挺费劲

**Comment by BeginnerSlob** [comment]
哪个都不想动了。。。这个issue就开着吧

**Comment by Leucothea** [comment]
并到背的issue里 这个先关了
