### ISSUE TITLE
武将削弱 - 第一弹

### ISSUE THREAD

**Issue by Leucothea** [BeginnerSlob/TouhouTripleSha#162]
- [x] 神秦心
肃狐：摸牌阶段开始时，你可放弃摸牌，改为将牌堆顶的一张牌面朝上置于你的人物牌上，称为“面”，然后进行一个额外的出牌阶段。
改为：摸牌阶段开始时，你可放弃摸牌，改为将牌堆顶的一张牌面朝上置于你的人物牌上，称为“面”，**然后你可以使用一张手牌**。

- [x] 古明地觉
洞悉：准备阶段开始时，你须失去上一回合以此法获得的技能，（后略）
改为：准备阶段开始时，你须失去**上一次**以此法获得的技能，（后略）

- [ ] 岛风
魔闪：（前略）须将装备区的防具牌交给一名其他角色，然后获得一名其他角色的一张牌。
改为：（前略）须将装备区的防具牌交给一名其他角色，然后获得一名其他角色的一张牌（**每回合只能以此法获得至多三张牌**）。

- [ ] 莉西娅
燕语：一名角色的出牌阶段开始时，（后略）
改为：**你或你攻击范围内的**一名角色的出牌阶段开始时，（后略）

- [ ] 弥生
幻略：出牌阶段限两次，你可以将包含至少一张锦囊牌的两张牌当一张非延时类锦囊牌使用。（后略）
改为：出牌阶段限两次，你可以将包含至少一张锦囊牌的两张牌当一张**除【贤石点金】外的**非延时类锦囊牌使用。（后略）

- [ ] 绵月丰姬
归墟：结束阶段开始时，若你此回合使用的最后一张牌是锦囊牌，你可以将场上的一张牌移动到另一名角色的区域内的相应位置。
改为：结束阶段开始时，若你此回合使用的最后一张牌是锦囊牌，你可以将场上的一张牌移动到**除你以外的**另一名角色的区域内的相应位置。

- [ ] 椎名真白
灵绘：阶段技。你可令一名其他角色摸一张牌，然后弃置一张手牌，你可弃置一至三张与该牌颜色相同的手牌，并令等量角色依次摸两张牌。
改为：阶段技。你可令一名**其他角色弃置一张手牌**，你可以弃置一至三张与该牌颜色相同的手牌，**并令包括该角色在内的**等量角色依次摸两张牌。

- [ ] 神青蛙
祀祟：专属技。准备阶段开始时，你可以令所有其他角色各弃置一张手牌，你从弃牌堆获得这些牌中的至多三张牌，然后你可以依次交给一名其他角色。
改为：专属技。准备阶段开始时，你可以令所有其他角色各弃置一张手牌，你从弃牌堆获得这些牌中的至多**两张牌**，然后你可以依次交给一名其他角色。

- [ ] C.C.
墨魂：觉醒技。结束阶段开始时，若你于此回合使用了至少两张花色相同的【杀】，你须减少1点体力上限，然后获得技能“黑棺”。
改为：觉醒技。结束阶段开始时，若你于此回合使用了至少两张花色相同的【杀】，你须减少1点体力上限，**弃置全部手牌**，然后获得技能“黑棺”。

- [ ] 少名针妙丸
宝锤：其他角色的出牌阶段开始时，若你有手牌，你可令其交给你一张手牌，（后略）
改为：其他角色的出牌阶段开始时，若你有手牌**且不大于三张**，你可令其交给你一张手牌，（后略）

- [ ] 尤瑞艾莉
断逆：阶段技。你可以选择你在其攻击范围内的一名角色区域内的一张牌，令其将此牌当【杀】对你使用，你可以为此【杀】额外指定一个目标。
改为：阶段技。你可以选择你在其攻击范围内的一名角色区域内的一张牌，令其将此牌当【杀】对你使用，**若其体力值不小于你**，你可以为此【杀】额外指定一个目标。

- [ ] 神八云紫
灵殒：（前略）1.【绯想镜诗】－“崩坏”；2.【碎月绮斗】－“散灵”；3.【妙手探云】－“心殇”；4.【赤雾锁魂】－“禁恋”。
改为：（前略）1.【绯想镜诗】－“崩坏”；2.【**灼狱业焰**】－“散灵”；3.【**心网密葬**】－“心殇”；4.【赤雾锁魂】－“禁恋”。

**Comment by BeginnerSlob** [comment]
就差lang了@Leucothea
