### ISSUE TITLE
进度条

### ISSUE THREAD

**Issue by Leucothea** [BeginnerSlob/TouhouTripleSha#175]
己方的不用改
其他角色的进度条 往下挪5个像素
小分辨率就自己看着挪吧。。。

**Comment by BeginnerSlob** [comment]
你自己改skins呗，
skins/defaultSkin.layout.json
photo部分 progressBarArea，而且你甚至可以用progressBarHorizontal改成竖的

**Comment by Leucothea** [comment]
除了这个文件还有什么文件要改的

**Comment by BeginnerSlob** [comment]
改完记得close
