### ISSUE TITLE
索菲 材音

### ISSUE THREAD

**Issue by shamosha** [BeginnerSlob/TouhouTripleSha#188]
莉西娅 发动“燕语”弃置了 闪[￼J]
索菲 发动了“材音”弃置了 杀[￼J]，目标是 莉西娅
莉西娅 发动了“燕语”，目标是 羽衣狐
羽衣狐 从 索菲 处获得 杀[￼J]
羽衣狐 发动了“万祢”将 杀[￼J] 当成 杀[￼J] 使用，目标是 留佳
羽衣狐 对 留佳 造成了 1 点伤害[无属性]
留佳 体力为 2 ，体力上限为 4
留佳 发动了“骚嚣”
羽衣狐 选择了 红桃
留佳 展示了 心网密葬[￼3]
留佳 使用了 心网密葬[￼3]，目标是 莉西娅
留佳 弃置了 莉西娅 的卡牌 桃[￼7]

主机炸了

**Comment by BeginnerSlob** [comment]
这个时候莉西亚没牌了吧。。
