### ISSUE TITLE
有人进出后不能添加ai

### ISSUE THREAD

**Issue by Leoongithub** [BeginnerSlob/TouhouTripleSha#19]
原因貌似是计数的问题，比如6人局有三个人，如果有一个人退了，还是只能加3个ai，再进来一个人就只能加2个ai，以此类推。
怀疑与roomscene.cpp中的void RoomScene::addRobot()函数里的ClientInstance->getPlayers().length()有关。

**Comment by Fsu0413** [comment]
。。。这个bug。。。看我在V2的修改吧，添加全部AI放到服务器了
