### ISSUE TITLE
UI BUG 阵亡后头上的「救救我」不消失

### ISSUE THREAD

**Issue by Misaka2623** [BeginnerSlob/TouhouTripleSha#191]
神蕾米对神秦心使用火攻，神秦心扣血触发「忿狼」摸牌触发「忧狸」掉血死亡，神蕾米回合结束后神秦心头上的「救救我」图案依旧不消失，之后大约一圈后，也许是神秦心离线后，救救我的图案消失（具体什么时候没注意）
录像文件有存，可以找我要

以防万一贴个log

----------
神蕾米莉娅 摸了 2 张牌
神蕾米莉娅 使用了 妙手探云[￼6]，目标是 桑妮
神蕾米莉娅 从 桑妮 处获得 雷杀[￼7]
神蕾米莉娅 使用了 百鬼夜行[￼7]，目标是 远野秋叶, 亚里亚, 莉莉姆, 黑羽宁子, 蓬莱山辉夜, 神秦心, 桑妮
神蕾米莉娅 对 远野秋叶 造成了 1 点伤害[无属性]
远野秋叶 体力为 4 ，体力上限为 5
远野秋叶 发动了“梦玄”
远野秋叶 摸了 1 张牌
神蕾米莉娅 对 亚里亚 造成了 1 点伤害[无属性]
亚里亚 体力为 3 ，体力上限为 4
神蕾米莉娅 对 莉莉姆 造成了 1 点伤害[无属性]
莉莉姆 体力为 2 ，体力上限为 3
莉莉姆 发动了“恩怨”
神蕾米莉娅 失去了 1 点体力
神蕾米莉娅 体力为 2 ，体力上限为 4
黑羽宁子 打出了 杀[￼6]
蓬莱山辉夜 打出了 雷杀[￼6]
神蕾米莉娅 对 神秦心 造成了 1 点伤害[无属性]
神秦心 体力为 1 ，体力上限为 3
神秦心 的“忿狼”被触发
神秦心 回复了 1 点体力
神秦心 体力为 2 ，体力上限为 3
神秦心 摸了 2 张牌
神秦心 的“忧狸”被触发
百鬼夜行[￼7] 被作为 面 牌移出游戏
神秦心 的“忧狸”被触发
闪[￼J], 百鬼夜行[￼7] 被置入弃牌堆
神秦心 失去了 1 点体力
神秦心 体力为 1 ，体力上限为 3
桑妮 打出了 杀[￼6]
神蕾米莉娅 使用了 灼狱业焰[￼2]，目标是 神秦心
神秦心 展示了 火杀[￼5]
神蕾米莉娅 弃置了 杀[￼4]
神蕾米莉娅 对 神秦心 造成了 1 点伤害[火属性]
神秦心 体力为 0 ，体力上限为 3
神秦心 的“忿狼”被触发
神秦心 回复了 1 点体力
神秦心 体力为 1 ，体力上限为 3
神秦心 摸了 2 张牌
神秦心 的“忧狸”被触发
断灵御剑[￼Q], 净琉璃镜[￼2] 被作为 面 牌移出游戏
神秦心 的“忧狸”被触发
断灵御剑[￼Q], 净琉璃镜[￼2] 被置入弃牌堆
神秦心 失去了 1 点体力
神秦心 体力为 0 ，体力上限为 3
神秦心 濒死求桃，一共需要 1 张【桃】
神秦心【异端】死亡，无伤害来源
神秦心 弃置了 闪[￼4], 闪[￼6], 火杀[￼5], 火杀[￼7], 坤神天叶[￼K]
神秦心 失去了装备区的 坤神天叶[￼K]
碎月绮斗[￼A] 被置入弃牌堆
神蕾米莉娅 使用了 火鼠裘[￼2]
神蕾米莉娅 装备了 火鼠裘[￼2]

**Comment by Fsu0413** [comment]
以前神杀有个死亡时延时锦囊不消失的问题，怀疑是avatar被setDisabled了

**Comment by BeginnerSlob** [comment]
这个问题不管了，问题不大
