### ISSUE TITLE
赫萝加强改动

### ISSUE THREAD

**Issue by MonsterShrubs** [BeginnerSlob/TouhouTripleSha#225]
原【知惠】: 每当你受到伤害时，你可弃置一张♥手牌并将此伤害转移给一名其他角色，若如此做，该角色在伤害结算后摸X张牌（X为该角色已损失的体力值）。
【知惠】：当你受到伤害时，你可弃置一张♥手牌并选择一名其他角色，然后你选择一项：
1.将此伤害转移给其，然后其在伤害结算后摸X张牌（X为其已损失的体力值且至多为5）；
2.防止此伤害，令其失去一点体力，然后其获得你弃置的牌。

**Comment by MonsterShrubs** [comment]
原【知惠】: 每当你受到伤害时，你可弃置一张♥手牌并将此伤害转移给一名其他角色，若如此做，该角色在伤害结算后摸X张牌（X为该角色已损失的体力值）。
【知惠】：当你受到伤害时，你可弃置一张♥手牌并选择一名其他角色，然后你选择一项：
1.将此伤害转移给其，然后其在伤害结算后摸X张牌（X为其已损失的体力值且至多为5）；
2.防止此伤害，令其失去一点体力，然后其获得你弃置的牌。

**Comment by YNawa** [comment]
未必需要如网杀般移植新小乔。天香新效果完全改变了小乔原打法。
