### ISSUE TITLE
要求二妹强度调整

### ISSUE THREAD

**Issue by blackll7** [BeginnerSlob/TouhouTripleSha#229]
理由，

无视距离的2顺对于全摸牌白或者耐久向武将以及回合外强将的压制太为致命，且一但发动容易卡手的红桃会使其完全变为二妹的牌库。且由于获取的是两牌而不是两手牌，使二妹原本设计的低防御靠觉醒和4血保命变为了优秀的控场控距离能力。

而血艺对回合内强将同样可以做到压制，可以说是过于攻守兼备。而觉醒和四血我就不说了，纯算填。
二妹作为集控距离，控制回合内行动，控手牌于一体的四血武将，要类比的话可以用四血的张郃来对比，同样2顺 张郃需要损失3牌，1顺的移动武器也需要损失1牌，而二妹只需损失1红桃即可达到这两者的功效还比人家多了主动乐人和觉醒的能力，张郃算是强度尚可，那二妹怎么能说不说过强了呢？

就算（把二妹）改成三血无觉醒二妹也不能说弱。我认为应该给禁果1技能的发动条件加以限制，改为已损失体力的武将 或者 对与自己距离为1的武将发动 为好（最好二牌改成二手牌）。

（我认为设计上既没有考虑到红桃牌多为不可主动使用牌的问题也没有考虑到诱导敌人舍弃红桃牌所损失的收益（张郃也就撑死压制部分位置的敌人的丢兵乐）。拿白摸红桃率去衡量二妹技能的发动率来进行技能设计是完全错误的。）
EX，哪个改的（或摸一牌啊）， 这不是越改越强了吗？

**Comment by BeginnerSlob** [comment]
@blackll7 麻烦排一下版，用一下markdown或者再不济写出来1、2、3点或者回车空格，你这个很影响阅读

**Comment by BeginnerSlob** [comment]
顺便@shamosha @Leoongithub

**Comment by BeginnerSlob** [comment]
@blackll7 或摸一明显是削弱啊，让目标多了一个选择，对目标来说是选择多了，对使用者来说不就是削弱吗

**Comment by blackll7** [comment]
首先二妹的打法就是控一个打一个，面临的问题则是猜测对面存不存在卡手的红桃的问题。给与对面无主动用牌能力武将一张牌可以很好的帮助对面至少保留两张或以上的牌，增大技能的发动率。

**Comment by BeginnerSlob** [comment]
建议
阶段技。你可以选择一项：1.获得于此回合内的〖血呓〗〈你可以将一张♥牌当【春雪幻梦】使用〉；2.将一张红色手牌交给一名角色▶你获取该角色的两张牌，然后其回复1点体力，若这些牌都为红色，你再失去1点体力。

**Comment by YNawa** [comment]
建议。
【一技】你可以跳过出牌阶段并选择一项：1.将至多两张红色牌当乐贴给等量其他角色。
2.将一张红色牌交给一名角色，再获得其两张牌。若其中有装备牌，你可以使用之。

**Comment by YNawa** [comment]
我个人拟采用这一方案：
以改帝方案为底本
出牌阶段开始时，你可以选择一项：1.获得于此回合内的〖血呓〗〈阶段技，你可以将一张♥牌当【春雪幻梦】使用〉；2你可以弃置一张一张♥牌▶你获取一名角色的两张牌，然后其回复1点体力。若你作出了选择，此阶段结束时你需展示所有手牌并弃置其中所有的红桃牌。
觉醒技不变。
请酌
