### ISSUE TITLE
8.9BUG列表

### ISSUE THREAD

**Issue by BeginnerSlob** [BeginnerSlob/TouhouTripleSha#230]
- [x] 凌统回合内2牌也能旋风 by 雯雯
- [ ] 深雪展示基本牌，只让弃置锦囊 by 性欲
- [x] 坏灭bug by ???
- [x] 刘备需要加入出牌限制 by 改帝
- [x] 相邻角色 by Slob
- [x] 幻胧效果持续 by Slob
- [x] 展示多张手牌Footnote by Leo
- [x] 竭盈Compulsory by Slob
- [x] 鬼缠 by Leo
- [x] 佚响 by 同声
- [x] 怪奇 by Slob

**Comment by Leoongithub** [comment]
- [ ] 先神爱再杀可以2杀，反之不行。

**Comment by Leoongithub** [comment]
- [ ] ai bug
![q7o 9c _v n0lcu l jb42](https://user-images.githubusercontent.com/10937162/39390207-de638b08-4ac3-11e8-9636-ea97e7995724.png)

**Comment by BeginnerSlob** [comment]
AI问题有很多，再说吧

**Comment by BeginnerSlob** [comment]
展示多张手牌footnote
