### ISSUE TITLE
天空璋与凭依华新将DIY收集

### ISSUE THREAD

**Issue by YNawa** [BeginnerSlob/TouhouTripleSha#231]
高丽野阿吽 4 设：Slob
【一】—你可以将武将牌翻面，视为使用一张【无懈可击】（以此法使用的【无懈可击】不是【无懈可击】的合法目标）。
【二】—锁定技。当你的武将牌背面向上时，你受到的伤害+1。
【三】—限定技。当你受到的伤害结算开始时，你可以将人物牌翻面。

高丽野阿吽 3 设：乳白
【一】—当一名角色在出牌阶段使用了等于你当前体力值的牌，你可以选择是否在之后承受本回合所有角色受到的伤害。
【二】—当你受到伤害后，获得【三】直到回合结束。若伤害值大于1，你回复1点体力。
【三】—当你受到伤害时，你可以弃置一张牌。若如此做，伤害来源需选择：弃置一张相同的牌；或令你摸一张牌并防止此伤害。

高丽野阿吽 4 设：花店
【—】—锁定技。游戏开始时，你拥有【阿】标记（此标记背面为【吽】标记）。你的每个结束阶段开始时，你将标记翻转。
【二】—锁定技。若【阿】标记向上，你于出牌阶段使用的牌在结算完毕后需置于你的武将牌上，称为“神”；你于弃牌阶段至少需弃置X张牌（X为你上个弃牌阶段弃置的牌数）。若【吽】标记向上，你需于出牌阶段开始时获得所有“神”并依次使用之，否则结束你的出牌阶段。

依神紫苑 4 设：改帝
【一】—你的回合开始时，你可以令一名角色获得A标记直到其下个回合结束。
（拥有A标记的角色拥有技能：锁定技，当你成为【杀】的目标时，若【杀】的使用者没有A标记，其获得A标记直到其下个回合结束。当你使用的【杀】被其他角色的【闪】抵消时，视为【闪】的使用者对你使用一张【杀】。）
【二】—拥有A标记的角色的弃牌阶段结束时，你可以交给其一张手牌，然后获得本回合因弃置而置入弃牌堆的两张牌。

依神女苑 3 设：改帝
【一】—阶段技。你可以令一名角色进行一个额外的出牌和弃牌阶段，你获得此额外弃牌阶段因弃置进入弃牌堆的所有牌。
【二】—锁定技。出牌阶段结束时，你令手牌上限+X直到回合结束（X为你此阶段获得的牌数）。

矢田寺成美 3 设：杜停杯
【一】—阶段技，你可以失去1点体力上限，令一名其他角色增加1点体力上限，然后其不是【一】的合法目标直到游戏结束。若你的当前体力因此减少，该角色回复1点体力。
【二】—觉醒技。结束阶段开始时，若你的体力上限为1，你失去【一】并获得【三】。
【三】—每回合限一次，你可以将一张手牌当任意一张基本牌或非延时锦囊使用，你不得选择已选择过的名称。你使用此技能的次数累计超过X次时，失去此技能并将体力上限调整为3（X为游戏人数）。

爱塔妮缇 4 设：改帝
【一】—阶段技。你可以将一张手牌置于武将牌上，称为“鳞”。其他角色计算与你的距离+X（X为“鳞”的数量且至多为2）。
【二】—摸牌阶段结束时，你可将手牌与“鳞”进行等量交换。你的回合结束时，你可弃一张“鳞”，摸两张牌。
【三】—锁定技。当你受到火焰伤害时，你需弃置所有手牌。

高丽野阿吽 4 设：桀
【一】—你可以跳过出牌阶段并将任意张点数和不大于13的非基本牌置于人物牌上，称为“X”。
【二】—出牌阶段，你可以弃置一张“X”并令一名其他角色选择：弃置一张非基本牌；或失去1点体力。

坂田合欢乃 4 设：改帝
【一】—每当与你距离1的角色使用【闪】抵消【杀】时，或受到1点伤害时，你可以弃置一张手牌，令【杀】和非延时锦囊对你与该角色无效直到当前回合结束。若如此做，该角色摸一张牌。
【二】—当与你距离1的其他角色于出牌阶段获得牌时，你可以弃置一张手牌，获取这些牌中的一张牌。

**Comment by BeginnerSlob** [comment]
emmmmmm
