### ISSUE TITLE
宇佐见莲子的修改

### ISSUE THREAD

**Issue by YNawa** [BeginnerSlob/TouhouTripleSha#243]
根据原设计者同声异谱的意见削弱其过强的摸牌能力。
**原技能：**
辨方——当你相邻的角色于其回合外失去手牌后，你可以摸一张牌。
知时——当你于回合外得到牌/失去手牌后，你可以亮出牌堆顶的一张牌▶你选择一项：1. 将之置于牌堆顶；2. 将之置入弃牌堆。
**新技能：**
辨方——当你相邻的角色于其回合外失去手牌后，**若你的手牌数不大于该角色**，你可以摸一张牌。
知时——当你于回合外得到牌/失去手牌后，你可以亮出牌堆顶的一张牌▶你选择一项：1. 将之置于牌堆顶；2. 将之置入弃牌堆。

**Comment by BeginnerSlob** [comment]
1技能白板了吧？

**Comment by BeginnerSlob** [comment]
感觉这个武将还要再改
