### ISSUE TITLE
加强SP映姬的草案

### ISSUE THREAD

**Issue by blackll7** [BeginnerSlob/TouhouTripleSha#244]
徨笏: 每当一名其他角色需要使用或打出一张【闪】时，你可以弃置至少一张手牌，然后令该角色摸一张牌，若如此做你也无视合法性成为该杀的目标。 

凛要: 每当一名其他角色需要使用或打出一张【闪】时，若你的人物牌背面朝上，你可以弃置一张非基本牌并，将你的人物牌翻面，视为该角色使用或打出了一张【闪】。 

绯镜: 每当你失去最后的手牌时，你可将手牌补至等同于你体力上限的张数，然后将你的人物牌翻面。

**Comment by blackll7** [comment]
理由：上一个团队贡献0 不吃手牌结构 且杀几乎难以造成伤害的武将我想叫做仁王禁
这个将目前的问题在于1不动彻底白
2技能联动性过强，一方面在防御能力极强的条件下仍具有出杀把自己翻回来的带来的主动性我是反对的，另一方面，其虽然3血但是“闪”的威胁性实在太高而且最不正确的设计是其使用闪后拥有的过牌，摸牌能力使其真正意义上的solo无解。（衡量：星SP云妹，新张角，同样在于杀难以对其造成伤害形成的高防御的单挑能力，但是这两者均需要一定的手牌规划并且在低血线条件下其防御能力大打折扣。而目前这将完全不惧手牌损失基本上可以说是界云和张春华合体级别的产物）

**Comment by BeginnerSlob** [comment]
我觉得还是吃手牌结构的，因为需要出【闪】来弃牌

**Comment by blackll7** [comment]
不一样，其他两位会由于手牌结构被压到1而难以为继，这个本身威慑的提供的是再次发动威慑力的过牌摸牌能力，不可同日而语

**Comment by 1061059766** [comment]
等等如果这么改了以后1 2技能不能同时触发？
