### ISSUE TITLE
DIY正选技能稿

### ISSUE THREAD

**Issue by YNawa** [BeginnerSlob/TouhouTripleSha#246]
- [x] SHIN018 花
近于神的蝴蝶  爱塔妮缇拉尔瓦
3体力 空属性 设：同声异谱
【蝶影】：结束阶段开始时，若你于本回合使用的牌均为同一类别，你可弃一张牌，对一名未受伤的角色造成1点伤害。
【比翼】：阶段技。你可以指定任意名体力值之和不大于3的角色，令这些角色各摸一张牌。

- [x] SHIN022 花
渡世的山姥  坂田合欢乃
4体力 空属性 设：永恒的须臾
【鬼咒】：你使用的【杀】可以额外指定X名目标（X为体力值为1的角色数）。
【刃磨】：出牌阶段，你可以重铸一张装备牌并选择：令你的攻击范围+1直到此回合结束；或本回合使用【杀】的次数上限+1。

- [x] SHIN019 雪
神荼郁垒  高丽野阿吽
4体力 空属性 设：桀
【吐纳】：你可以跳过出牌阶段并将任意张点数和不大于13的非基本牌置于人物牌上，称为“翕”。
【狞顾】：出牌阶段，你可以弃置一张“翕”并指定一名其他角色。该角色需选择：弃置一张非基本牌；或失去1点体力。选择完成后，其于此回合内便不是“狞顾”的合法目标。

- [x] SHIN023 雪
垂迹的地藏  矢田寺成美
3体力 空属性 设：雾之湖的小沐
【灭已】：当其他角色使用【杀】指定你为目标时，你可令此【杀】无效。若如此做，视为其对你使用一张【碎月绮斗】（此【碎月绮斗】不是【三滴天粒】的合法目标）。
【辻立】：出牌阶段开始时，你可以亮出牌堆底的两张牌。若为同色，你可以将这些牌当一张无距离限制的【杀】使用或弃置之；若为异色，你可以获得其中一张，然后弃置另一张。

- [x] SHIN017 风
危险的舞者  尔子田里乃＆丁礼田舞
3体力 空属性 设：宛若改帝
【翾缦】：锁定技。分发起始手牌时，额外发给你两张牌。然后你从手牌中选择三张置于武将牌上，称为“舞”。每当你使用、打出或弃置手牌后，你需将手牌与“舞”替换。你每发动四次【翾缦】，你摸一张牌。
【狂舞】：阶段技。你可以摸一张牌并弃置一张牌，然后摸一张牌并弃置一张牌。若以此法弃置的两张牌均为手牌且颜色相同，此回合结束时你便可摸一张牌并将一张手牌作为“舞”置于武将牌上，然后弃置一张牌。

- [x] SHIN021 风
究极的秘神  摩多罗隐岐奈
3体力 幻属性 设：怪若樲棂
【神呼】：每当你造成或受到一次伤害后，你可以与一名其他角色拼点，若你赢，视为你对其使用一张【罔两空界】（你不执行摸牌效果）；若你没赢，其摸一张牌。然后其于此回合内便不是“神呼”的合法目标。
【后户】：当一次拼点结算完毕后，你可以摸一张牌。

- [x] SHIN020 月
追想之春  依神紫苑
4体力 空属性 设：名和行年
【穷乏】：锁定技。游戏开始时，你拥有“贫”标记（有“贫”标记的角色拥有技能“赤贫”和“哀悯”）；当前存活人数不大于2时，将场上的“贫”标记弃置，你摸两张牌。
【赤贫】：锁定技。摸牌阶段摸牌时，你少摸一张牌。
【哀悯】：阶段技。若你的手牌数为全场最低，你可以令所有其他角色依次决定是否交给你一张手牌。若你以此法获得牌后手牌数不为全场最低，你将“贫”标记交给一名其他角色。

- [x] SHIN024 月
清朴之秋  依神女苑
3体力 空属性 设：花店
【欲炽】：其他角色的出牌阶段开始时，若其位于你攻击范围内，你可以令其选择：是否交给你一张手牌并视为对其攻击范围内的一名角色使用【杀】。若其手牌数多于你，其必须选择交给手牌。
【散财】：锁定技。每当你于摸牌阶段外获得牌后，若你的手牌数大于手牌上限，你须弃置手牌至手牌数不大于手牌上限。

**Comment by blackll7** [comment]
SHIN017 花
近于神的蝴蝶妖精 爱塔妮缇拉尔瓦
3体力 空属性 设：同声异谱&此人不搞基
【蝶影】：出牌阶段结束时，若你于此阶段使用的牌均为同一类别，你可对一名未受伤的角色造成1点伤害。
【比翼】：阶段技。你可以指定任意名体力值之和不大于3的角色，令这些角色各摸一张牌。

强度过高。
强命的设计不能按照简单的一血=2牌啊，还包括对对方手牌结构和防御性技能的压制作用上。
无距离限制，低发动限制的强命体验会非常的不好，对即使对非满血将才能发动也是极大地压制了敌人手牌管理的空间。2技能一样，发动条件为0，全程1为主残局可能2-3。即便按照简单的1血2牌规则换算回合收益稳定3以上。这都啥跟啥的强度啊。

**Comment by BeginnerSlob** [comment]
ls+1
建议改成结束阶段，弃1打1伤

**Comment by YNawa** [comment]
已改

**Comment by blackll7** [comment]
【欲炽】：其他角色的出牌阶段开始时，若其位于你攻击范围内，你可以令其选择：是否交给你一张手牌并视为对其攻击范围内的一名角色使用【杀】。若其手牌数多于你，其必须选择交给手牌。
质疑下，一个是“若其位于你的攻击范围内”是否为“若你唯于其攻击范围内”
一个是若强制交予手牌是否强制出杀。

**Comment by BeginnerSlob** [comment]
霸对年理解：
1. 这个问题不大，我觉得是字面意思
2. 强制出杀

**Comment by blackll7** [comment]
那么问题来了，作为一个非锁定技提供二刀光环+杀转换的效果代价为队友间的1顺（0到-1收益）是否严重失当？

**Comment by BeginnerSlob** [comment]
这个将最多3血吧，4血有点过分了

**Comment by YNawa** [comment]
原本是4血没攻击范围限制 后来狼烟佬说强我就砍了这么一刀 现在觉得还强就再砍一血

**Comment by BeginnerSlob** [comment]
3血然后杀计入使用限制吧，我觉得

**Comment by YNawa** [comment]
计入使用限制也可

**Comment by BeginnerSlob** [comment]
在你游环境不断杀太强了

**Comment by blackll7** [comment]
干脆把1技能改锁定

**Comment by blackll7** [comment]
追加意见：
【翾缦】：锁定技。分发起始手牌时，额外发给你两张牌。然后你从手牌中选择三张置于武将牌上，称为“舞”。每当你使用、打出或弃置手牌后，你需将手牌与“舞”替换。你每发动四次【翾缦】，你摸一张牌。
☞【翾缦】：锁定技。分发起始手牌时，额外发给你两张牌。然后你从手牌中选择三张置于武将牌上，称为“舞”。每当你使用、打出或弃置手牌后，你需将手牌与“舞”替换。你每发动四次【翾缦】，你摸一张牌。摸牌阶段若你的武将牌上没有“舞”你需跳过你的摸牌阶段并摸两张牌作为“舞”置于你的武将牌上。

**Comment by blackll7** [comment]
SHIN023 月
追想如昔春依旧 依神紫苑
4体力 空属性 设：名和行年
【穷乏】：锁定技。游戏开始时，你拥有“贫”标记（有“贫”标记的角色拥有技能“赤贫”和“哀悯”）；当前存活人数不大于2时，将场上的“贫”标记弃置，你摸两张牌。
【赤贫】：锁定技。摸牌阶段摸牌时，你少摸一张牌。
【哀悯】：阶段技。若你的手牌数为全场最低，你可以令所有其他角色依次决定是否交给你一张手牌。若你以此法获得牌后手牌数不为全场最低，你将“贫”标记交给一名其他角色。

追加意见：
游戏开始时你可以转让该标记 理由，开场身份不明你的技能不会得到别人的响应支持，导致第一轮白板，其次环境中存在强用牌武将或遇到快节奏局时该技能发动率存疑。本身收益不是很高的条件下再带上一轮白板供选率太堪忧了。ps其实身份适应性成谜，主内都不适格，忠环境下没有明确可以配合的主，反能力一般吧。

**Comment by MonsterShrubs** [comment]
还行吧，不考虑其他的拼点技情况下，无损拼点（拆手牌）没变，削了对方留点压力，以及自身的刷换牌能力，测重了拼点资源，而弱化了拼点结果
