### ISSUE TITLE
提议sp爱丽丝削弱方案

### ISSUE THREAD

**Issue by MonsterShrubs** [BeginnerSlob/TouhouTripleSha#248]
【偶祭】: 每当你或你攻击范围内的一名角色的装备区于你的回合内改变时，你可以选择一项：弃置一名其他角色的一张手牌；或摸一张牌。
→【偶祭】: 每当一名角色的装备区**内的武器牌或防具牌**于你的回合内改变时，你可以选择一项：弃置一名其他角色的一张手牌；或摸一张牌。

**Comment by BeginnerSlob** [comment]
距离限制去掉，然后加上武器牌和防具的限制

**Comment by MonsterShrubs** [comment]
同意，改了

**Comment by blackll7** [comment]
等等等。。。SP爱丽丝不是因为爆发牌差不合理导致的强度过高吗。。。。你们这改了等于没改。。丝毫没有缓和爆发的巨额牌差啊。。。。

**Comment by blackll7** [comment]
最大的问题在即使不考虑其他人的联动，SP小爱本身的技能联动可以产生的异常牌差，
即 在2技能稳定发动2次1技能的前提下，由于1技能的发动条件使牌堆中的 过河拆桥 和 装备牌 都成为 高收益牌。
由于1技能发动可以摸牌，进一步增大了连续发动的几率。本身3血无防御一回合摸4确实不是说怎么怎么强，但是触发条件低，技能会导致其他牌收益增高和无惩罚发动这三者合一才是SP小爱的问题。

我的意见：摸1一回合只能执行一次。就这样，直接把扩展可能给按死结束，免得收益不好算。

**Comment by MonsterShrubs** [comment]
只能选择武器和装备本身也是减少摸牌数啊

**Comment by blackll7** [comment]
说白了SP爱丽丝目前的状况就是小枭姬+小集智但是又有基础额外摸2。。。。。我这样说的话应该能更好地理解这个问题。。。。1技能的爆发效果和这两个技能选择其中之一差不多，非要理解的话就是自带刘备包养的孙尚香OR黄月英这样说的话就很好理解为什么SP小爱爆发不合理了

**Comment by blackll7** [comment]
设计考量上来说，以牺牲红色基本牌即牺牲防御换取的是高牌量（高防御）不能说是很合理的设计吧。。
