### ISSUE TITLE
提议琪露诺加强方案

### ISSUE THREAD

**Issue by MonsterShrubs** [BeginnerSlob/TouhouTripleSha#249]
发动【寒魄】的时候，在不配合大招的情况下，本身只能通过【杀】被【闪】，或减少对方牌的锦囊，在技能先预警的情况下，达到2张触发【寒魄】翻面效果并不理想，被群友冠名四废之一，在此提议加一个新技能。

【争冠】: 阶段技。你可以指定距离为1的一名角色，令其摸一张牌，然后视为你对其使用一张不计入使用限制的【杀】，此【杀】造成伤害时，你防止此伤害并摸一张牌，然后其弃置一张手牌。

**Comment by blackll7** [comment]
9的问题嘛。。。。不是经典的伪强命武将强度问题嘛。我个人看法是强度没啥问题，反正技能收益再高也是在博弈中劣势地位被抑制发动。你这个加强法也是明显的过强了。

我认为合适的加强：出牌阶段你可以弃置一张黑桃手牌，视为你装备了寒冰剑直到下回合开始。

**Comment by blackll7** [comment]
因为9的技能够强了，再来个免费的距离+技能发动器还是限制下条件为好。
