### ISSUE TITLE
提议恋的加强方案

### ISSUE THREAD

**Issue by MonsterShrubs** [BeginnerSlob/TouhouTripleSha#250]
现在这个方案的恋，我是不认为其有什么爆发的价值，除去刷起手之外，能触发的牌-弓，明光铠，赤兔，桃（非满血）可对自己发动，至于对队友发动的基本除了濒死的桃，但是基本摸不了牌，红杀，声东，过河，也很少选择队友为目标，更别说能摸多少了。

当前版本我觉得不如类比一下以前那个给红桃然后摸牌的那个版本，以前是因为有时候自身摸不了红桃而导致白板2回合不等，所以才有加强的念头（当然加强过头了）

故在此我提我的方案：
原【埋火】: 当你使用♥牌指定唯一目标后，你可以选择一种花色，然后展示该角色手牌，其中每有一张该花色的牌，该角色摸一张牌（至多摸三张）。 
新【埋火】：当你使用红色牌后，若此牌为你于此回合内使用的第一张牌，你可以选择一种花色，然后展示一名角色的手牌，其中每有一张该花色的牌，该角色摸一张牌（至多摸三张），若不在你的回合内，你不可选择你为目标。

**Comment by blackll7** [comment]
说下我的看法。。。恋恋的问题在于技能发动收益位于随机分布手牌时确实是合理的，但是实际上已知的自己的手牌和偏红的回合外手牌导致这个技能收益失控才让这个技能被砍的（说不好听就是根子烂）。

提案：1追加技能，当你需要使用一张牌时，你可以弃置一张“红桃”手牌，若如此做你使用的下一张牌花色视为红桃。
           2 你可以选择一种花色☞ 你可以选择，黑桃，梅花或者红桃

**Comment by MonsterShrubs** [comment]
1的存在，变成一个伪爆发伪过刷的存在，特别容易和上装备挂钩，感觉耐人寻味

**Comment by blackll7** [comment]
2的修改案可以很好的抑制这种不受控的爆发
