### ISSUE TITLE
擂鼓加强提议

### ISSUE THREAD

**Issue by MonsterShrubs** [BeginnerSlob/TouhouTripleSha#253]
方案1：失去装备区内的武器牌或防具牌，你可以摸一张牌。
方案2：当你装备区内的武器牌因其他角色弃置而进入弃牌堆时，你可以将一张同花色的手牌替换之。

**Comment by JiEIyo** [comment]
方案3：摸牌阶段前，你装备区没有装备，可以弃置一张和场上装备牌颜色相同的手牌，并挪置到你装备区。

**Comment by MonsterShrubs** [comment]
方案4：锁定技。当你的装备区于你回合内变动后，其他角色于你下回合开始之前不能弃置你装备区中的非宝物牌（或者非坐骑牌）。

**Comment by JiEIyo** [comment]
方案5：如果你装备区域装备少于或者等于1，你被弃置或者获得的牌用牌堆顶的牌代替。

**Comment by MonsterShrubs** [comment]
目前虫娘软定方案4

**Comment by blackll7** [comment]
4太绫操了。。。。如果方案4起码不能两回合连续发动或者限制只保护刚换上的

**Comment by BeginnerSlob** [comment]
其实我本意，并不限定于回合内，也就是不会被连拆两张
