### ISSUE TITLE
响子独立设计（等待批判中的）草案

### ISSUE THREAD

**Issue by blackll7** [BeginnerSlob/TouhouTripleSha#254]
坐等虫娘给差评

**Comment by blackll7** [comment]
响子
999

回音：锁定技，一名角色弃牌阶段结束时你必须将手牌补或弃置至X张（X为次回合该角色使用或弃置的卡牌个数且之多为6）。

幽谷：当一名角色使用一张基本牌响应其他角色的卡牌或技能时，你可以获得一个“音”标记，一名角色回合开始时你可以弃置1个“音”标记使【回音】失效直到本回合结束。

**Comment by blackll7** [comment]
响子

9999

回音：阶段技：出牌阶段你可以将一张手牌交给一名角色令其做出选择
1.将一张手牌交给一名在其攻击范围内且没有在本阶段获得牌的角色，并令其做出同样的选择。
2.受到你对其造成的一点伤害并获得技能“音击”直到另一名角色获得“音击”为止。
3.若你拥有技能“回音”，你可以摸一张牌。
（音击：锁定技，你的回合外你获取一张牌时你必须弃置一张手牌或流失一点体力）

**Comment by blackll7** [comment]
响子
9999
回音：当距离你为1的角色成为一张杀或者锦囊牌的目标时，你可以成为此牌的额外目标，若如此做该牌结算完毕后你可以获得并立即使用之。

**Comment by blackll7** [comment]
响子

999

回音：锁定技，游戏开始或你的回合开始时，你必需指定两名角色，其下一个出牌阶段对你以及距离你为1的角色使用的牌或出牌阶段弃置的非装备牌进入弃牌堆时你必需置于你的武将牌上称之为“音”。每有一张不同花色的音你的手牌上限便+1。

复咏：锁定技，你使用或打出与“音”同名的卡牌时，你需弃置全部的与该牌同名的音并摸一张牌

**Comment by blackll7** [comment]
响子
9999

【一】：锁定技，你的手牌上限为2。

【二】：当你以及你距离你为1的一名角色成为其他角色使用的一张牌的目标时，你可以你可以一张手牌正面向上置于你的武将牌上称之为"音"，若此“音”与该牌花色相同，你可以选择一名你攻击范围内的角色无视合法性成为此牌的额外目标。你可以将“音”作为手牌使用或打出。

**Comment by blackll7** [comment]
响子

999

音壁：阶段技，你可以指定一名角色其获得一个“回”标记，拥有“回”标记的角色出牌阶段结束时进行X次判定（X为你武将牌上“音”的数量），若为，你可以立即使用一张“音”，直到该角色死亡，你无法再次发动【音壁】。

音击：你对拥有“回”标记的角色使用的卡牌在结算后置于你的武将牌上称之为“音”，拥有“回”标记的角色死亡时，你弃置全部的“音”并摸等量的牌。

**Comment by blackll7** [comment]
响子

999

【一】：锁定技，你攻击范围外的角色使用或打出的非装备牌结算后你将其置于你的武将牌上称之为“音”，你攻击范围内的角色回合开始时，你将一张“音”置于牌堆顶。若你武将牌上的音不小于2X张，你弃置一张“音”并摸一张牌。
【二】：锁定技，你与其他角色计算距离时+X（X为当前存活角色数的一半向下取整）但你每拥有一张“音”你与其他角色计算距离时-1。回合结束时，你将你的武器牌置入手牌。

**Comment by blackll7** [comment]
响子
9999
回音：一名角色指定另一名角色为【杀】的目标时，你可以成为此【杀】的额外目标，若如此做视为视为你对该角色使用了一张【杀】。
复咏：对你使用了【杀】的角色出牌阶段结束时，若你与其一者没有在此阶段受到伤害另一者在此阶段受到了伤害时。你可以获得技能“垂迹”直到你下回合开始。然后摸一张牌并进行一个额外的弃牌阶段。

**Comment by blackll7** [comment]
响子
9999
回音：一名角色指定另一名角色为【杀】的目标时，你可以成为此【杀】的额外目标，若如此做视为视为你对该角色使用了一张【杀】。
复咏：对你使用了【杀】的角色出牌阶段结束时，若你与其一者没有在此阶段受到伤害另一者在此阶段受到了伤害时，你可以进行一次判定；
“方片”：你可以指定一名角色其可以弃置一张红色基本牌对你造成一点伤害然后令你回复两点体力。
“梅花”：你弃置其一张牌；
“黑桃”：其获得一个“溺”标记；
“红桃”：你回复一点体力；

**Comment by blackll7** [comment]
响子
9999
回音：锁定技，你响应技能使用牌时，你摸一张牌。

复咏：其他角色需要使用或打出一张基本牌时可以交予你两张牌或一张非基本牌若如此做你可以使用或打出一张该基本牌视为该角色使用或打出了该牌。

**Comment by blackll7** [comment]
响子
999
回音：回合开始时，你可以跳过你的摸牌阶段，若如此做你可以将武将牌翻面。

复咏：锁定技，你的武将牌背面朝上时，其他角色对距离你为1的角色使用的卡牌或距离你为1的角色在出牌阶段弃置的卡牌进入弃牌堆时，你必需置于你的武将牌上称之为“音”。你可以将“音”当作手牌使用或打出或弃置。你的武将牌由背面翻到正面时，你需弃置全部的“音”并摸等量的牌。你每有一种花色的“音”你与其他角色计算距离时-1。

**Comment by blackll7** [comment]
响子
999

音障：回合开始时你可以跳过你的出牌阶段，弃牌阶段，摸牌阶段然后将武将牌翻面。出牌阶段，你可以弃置一张手牌，使你的手牌上限+1直到回合结束。

复咏：其他一名角色回合结束时，若你的武将牌背面向上，你可以将武将牌翻至正面然后摸2+X张牌（X为该角色本回合使用牌的数量）然后执行一个出牌阶段和一个弃牌阶段，在这个出牌阶段你使用的牌不能超过X张，这个弃牌阶段你可以额外弃置至多X张牌。如果你在这个出牌阶段和弃牌阶段使用和弃置的牌数和该角色相同，你可以将武将牌翻面。

**Comment by blackll7** [comment]
来自 雯雯 的投稿

幽谷响子

9999

大声：锁定技，你使用的牌不会被点数小于这张牌的牌响应
2技能，出限1，你使用一张牌后可以选择一名角色，令其选择：对你选择的目标使用一张相同类型的牌；展示一张牌，若点数小于你使用的牌，则你获得其一张牌

**Comment by BeginnerSlob** [comment]
妈的，老子的投稿呢，雯雯的可以上，我的就不行？

**Comment by MonsterShrubs** [comment]
你直接在后面跟你自己的搞不就行了(

**Comment by blackll7** [comment]
来自 slob 的投稿

6血 响子
回响 锁定技。你的手牌上限为X（X为某标记数）。一名角色造成伤害后，你获得1枚某标记
复声 觉醒技。结束阶段开始时，若你的手牌上限大于体力上限，你减2点体力上限，失去 回响 ，获得 幻法。
XX 阶段技。你可以选择1～X名角色（x为某标记数），你令这些角色各弃1张牌，若一名角色以此法弃置手牌后，手牌小于体力值，你失去1个某标记。

**Comment by JiEIyo** [comment]
还差几个可以🔒了

**Comment by blackll7** [comment]
响子

9999

群友（复读机）：
若两个连续的回合内，当前回合角色均使用了【杀】，你可以摸一张牌然后弃置一张基本牌视为你使用了一张【杀】。
若两个连续的回合内，当前回合角色使用的【杀】均未造成伤害，你可以将弃牌堆中最近进入弃牌堆的一张【闪】交于一名角色。
若一名角色的回合内，当打出的【杀】超过两张时，你可以获得最近进入弃牌堆的一张【杀】并交给一名角色。

**Comment by blackll7** [comment]
响子 
9999
 
回音：若你在出牌阶段没有使用牌，出牌阶段结束时，你可以将至多3张手牌置于武将牌上称之为“回”，你的回合外当一张与“回”同名的卡牌进入弃牌堆时。你可以使用这张同名的“回”。

音壁：觉醒技，准备阶段开始时，若你的“音”数量大于你的体力值，你须减1点体力上限，然后获得技能“高音”。
（高音：出牌阶段，你可以指定一名角色展示一张手牌，你可以弃置点数之为其两倍以上的“回”，令该角色选择一项，弃置点数比你弃置的牌更多的牌，或受到你对其造成的一点伤害并令你摸一张牌。）
