### ISSUE TITLE
一莎成名2018 修改武将征集

### ISSUE THREAD

**Issue by YNawa** [BeginnerSlob/TouhouTripleSha#261]
本Issue列出上一阶段收集到的需要修改的武将，并附带其修改方向建议。投稿请参照建议进行修改，推重应尽量保持技能组的方向不变。

DIY武将（这些武将可以推重）：
1.堀川雷鼓（增强魔具成型的速度、几率或保持能力，本武将也可在大怪的Issue下【#253】发表看法或提出修改）
2.古明地恋（提高技能的发动率或改变其单一而尴尬的收益模式，本武将也可在大怪的Issue下【#250】发表看法或提出修改）
3.铃瑚（收益偏弱且没有有效的回合内创收时机）
4.高丽野阿吽（未定，本武将也可在桀佬的Issue下【#257】发表看法或提出修改）
5.依神女苑（目前的发动限制过多，但弱化某一限制又极有可能令其过爆，需慎重。本武将也可在大怪的Issue下【#258】发表看法或提出修改）
6.依神紫苑（修改方向是限制其团队间流动牌的能力。由于是我的设计，我先提出方案：改为“贫”标记在每轮的首次移动时才摸2牌。）
7.SP四季映姬（虽说理论上非常能闪能抗能控制，但自己是个超级不动白，浪费队友的出杀机会实现收益非常不划算。本武将也可在改帝的Issue下【#244】发表看法或提出修改。）
8.SP爱丽丝（怎么削了还是这么强？那就再削，不要顾及某摸鱼同声的面子。）
9.神古明地觉（0收益乃至负收益神将了解一下？赶紧增强吧。）
10.神四季映姬（虽然3D吧良将妙计赛的冠军设计非常有创意，但有意见认为，她作为神将到底还是欠缺了若干定鼎乾坤的“神性”。）
11.雪风·帕尼托尼（有意见认为这个表面上是控制的技能实则难以发挥，可以酌情改动）

三国杀武将（这些武将只允许改动，不允许推重）
1.朱鹮（王朗）（王司徒的确爆炸，怎么削大家看着办吧。）
2.黑雪姬（夏侯渊）（三刀夏侯渊不是很可取，我希望的是在已有思路上稍加改动。）
3.赤座灯里（于禁）（除了被赫卡提亚占住的那个于禁，其他版本的于禁都能作为原型。）
4.真红（曹洪）（提高技能的发动率、减少成本限制等等皆可。）
5.宫崎和香（旧马谡）（如何让挥泪发挥价值？）
6.沙耶（董卓）（其实我觉得董卓不弱。）
7.雷电（黄巾雷使）（如何将教主御用武将增强成一个泛用型武将？）
8.赤城（JSP马超）（这个也是因为JSP马超之前的脑杀结果过强而加了若干限制，但现在也有必要对这些限制进行一些商榷。）
9.阎魔爱（孙坚）（虽然有了英魂保底1，但改不了不动白问题。）
10.四糸乃（JSP孙尚香）（似乎是把原本的弱鸡改得过强了。）

**Comment by 1061059766** [comment]
3.铃瑚 4血 戋月——出牌阶段开始时，你可以视为使用【心网密葬】，若如此做，当目标因执行此【心网密葬】的效果而弃置牌后，你可以选择一项：1.令一名除你以外角色获取此牌，若如此做，获得此牌的角色在自身回合结束前不能使用、打出或弃置此牌；2.你结束出牌阶段，若如此做，该目标在自身回合结束前不能使用、打出或弃置与此牌相同类型的牌（借鉴杨修鸡肋）

**Comment by 1061059766** [comment]
11.雪风，改为3血，在原技能基础上增加类空城技能， XX（这个角色不熟想不出技能名...）：锁定技，当你于回合外没有手牌时，你不能成为非延时锦囊的目标

**Comment by 1061059766** [comment]
（4.真红，我感觉心眼直接简单粗暴的改成观4张挺好的0.0）
9.阎魔爱（孙坚），
方案一：直接考虑加个技能诈死？：在一名你的回合开始阶段，你可以选择失去x-1点体力（x为你现有体力值），若如此做，在你的下一名角色的回合结束阶段，你回复X点体力；
方案二：修改英魂，让他多发动几次？：其他角色的准备阶段开始时，若此时你已损失了x点体力，则你可以令该角色：1、摸x牌然后弃1牌，2、弃x牌然后摸1牌。每个角色每轮限1次，每轮限T减x次。（T为你此局游戏中的体力上限）（X为你已损失的体力值与1中的较大值）

**Comment by 1061059766** [comment]
6.沙耶，（我主要是感觉作为常备主她最大的作用是防速推，然而在莎莎杀有宝物汇卷的情况下不太可能被速推...建议改主公技？）舞华——君主技。当月势力角色造成伤害后，该角色可以进行一次判定，若结果为黑色，你可以选择回复1点体力或者摸2张牌。
然后还可以把幻呗的性别限制取消...
7.雷＆电 3血
XX——阶段技：二选一发动，①你可以将一张非属性【杀】当雷【杀】使用；②你可以将一张属性【杀】当【赤雾锁魂】使用。
YY——当一名角色受到属性伤害时，在此伤害结算以后，你可以令其进行一次判定，若结果为黑色，你对其造成一点无属性伤害；若结果为红色，你可以令场上一名角色获得此判定牌。 
10.四系乃，把觉醒技青赦的增加体力上限的效果去掉，回血可以不去。

**Comment by jkt401** [comment]
3.赤座灯里 
1号方案：技能发动次数由自己回合一次的基础上，自己的回合外每一圈能在别人的准备阶段再发动一次（这一点都不阿卡林:( ）
2号方案：回归以前的阿卡林 1.飘忽保留：你的回合外，当你攻击范围内的一名角色成为【杀】的目标时，你可弃置一张牌，或将该角色与你的人物牌横置，若如此做，将此【杀】转移给你。2.灯里的仁王盾技能效果改为，若你没有装备防具且需打出闪响应的牌是黑色杀，你可以视为你打出了闪。（我不知道这强不强）
3号方案：我还没想好

**Comment by jkt401** [comment]
5.宫崎和香
改为 限定技 当一名玩家死亡时，杀死该玩家的角色弃置其所有的牌，该技能在自己死亡时也可发动（反正已经不是马谡了，契合什么的不用在乎了）

**Comment by 1061059766** [comment]
9.神古明地觉
愈心——摸牌阶段开始时，你可以放弃摸牌，亮出牌堆顶的两张牌，然后获取这些牌，若这些牌均为红色，你可以令一名角色回复1点体力。
疮心——出牌阶段开始时，你可以弃置一张装备牌（还强了就改为弃置一张武器牌），获得于此回合内的〖灵视〗与〖闭月〗。
天心——回合开始时，你可以选择弃置一张牌，若如此做，你你可以观看牌堆顶的三张牌并调整这些牌的顺序并获取其中任意张♥牌，若以此法获得牌，你可以额外此回合内的获得于〖天妒〗。

**Comment by MataraOkina** [comment]
9.神古明地觉   体力上限：3
[愈心]：出牌阶段开始时，你可展示牌堆顶的三张牌，若如此做，当你于此阶段内使用牌时，若与其中（剩余的）一张牌花色相同，你可令一名角色摸一张牌。
[疮心]：锁定技，若你不是手牌数最多的角色，你拥有〖灵视〗；若你不是手牌数最少的角色，你拥有〖慎行〗。
[天心]：回合开始时，你可以弃置一至两张牌，选择X项（X为你以此法弃置的牌数）：1.声明〖虚视〗；2.声明〖精策〗。然后你于此回合内拥有你于此阶段内声明过的技能。

**Comment by MataraOkina** [comment]
SP爱丽丝·玛嘉特洛伊德   体力上限：3
[偶祭]：当一名其他角色于你的回合内失去装备区里的牌后，你可以弃置其一张手牌；当你失去装备区里的牌后，你可以摸一张牌。
[镜缘]——阶段技。你可以弃置一张基本牌并选择一至两名装备区里有牌的角色，令这些角色各选择一项：1.将装备区里的一张牌交给另一名角色；2.令你获得其一张手牌。

**Comment by JiEIyo** [comment]
雪风

**Comment by JiEIyo** [comment]
阎魔爱（孙坚）4血
白的话加个技能呗。
回合开始前，若你是全场体力最多或之一，你可以失去一点体力，获得一枚标记“魂”。当你受到濒死伤害时，你可以弃置一枚“魂”并防止此次伤害。
