### ISSUE TITLE
东方角色初稿

### ISSUE THREAD

**Issue by HakureiRin** [BeginnerSlob/TouhouTripleSha#264]
琪露诺
+【寒魄】：锁定技，防止你对其他角色造成的火焰伤害，防止你受到的火焰伤害。
【急冻】：出牌阶段开始时，你可以令一名其他角色摸等同于场上方块牌数的牌，然后弃置等量的牌。若如此做，此阶段结束时，若其于此阶段内失去过至少两张牌，其将人物牌翻面，然后摸一张牌。 
【冰爆】不变

SP爱丽丝
【偶祭】: 每当一名角色的装备区内的武器牌或防具牌于你的回合内改变时，你可以选择一项：弃置一名其他角色的一张手牌；或摸一张牌。

恋
【埋火】：当你使用红色牌指定唯一目标后，若此牌为你于此回合内使用的第一张牌，你可以选择一种花色，然后展示该角色手牌，其中每有一张该花色的牌，该角色摸一张牌（至多摸三张）。

雷鼓
+【鼓振】：锁定技。当你的装备区变动后，其他角色于你下回合开始之前不能弃置你装备区中的非宝物牌。

高丽野阿吽
【吐纳】：出牌阶段，你可以弃置一张“翕”并指定一名其他角色，该角色需选择：交给你一张非基本牌；或失去1点体力。然后其于此回合内不是“狞顾”的合法目标。 

女菀
【欲炽】：其他角色的出牌阶段开始时，（删去——若其在你的攻击范围内）你可以令其选择是否交给你一张手牌，并视为其对其攻击范围内的一名角色使用一张【杀】（计入使用限制），若其手牌数多于你，其必须选择交给你手牌。

神古明地觉
摸牌阶段开始时，你可以放弃摸牌，改为从牌堆顶亮出两张牌并获得之，若这两张牌均为红色，你可以指定一名角色令其选择一项：回复1点体力或摸两张牌。 

神四季映姬
【轮狱】：连舞技，当一张你不为其使用的目标（或之一）的牌置入弃牌堆时，你将这张牌置于牌堆顶，然后此阶段结束时你从牌堆底摸两张牌。 

铃瑚
【戋月】摸牌阶段或出牌阶段开始时，你可以视为使用一张【心网密葬】，该牌生效后，你可以选择一项：令目标角色获得被弃置的牌，且其此回合不能使用或打出该牌；或横置目标角色的人物牌，且结束当前阶段。

橙 3血  重推 diy：同声异谱
【遁甲】：当你成为一名其他角色使用牌的唯一目标后，若其装备区的牌比你少，你可以摸一张牌。
【晴明】：当你使用【杀】指定一名其他角色后，若其装备区的牌比你多，你可以取消之并视对其使用一张【木隐妖岚】、【妙手探云】、【心网密葬】或【碎月绮斗】。

稗田阿求
【墨迹】：当你需要使用或打出一张【杀】、【闪】或【酒】时，你可以将等同于你体力值数量的牌以任意顺序置于牌堆顶（至多两张），视为你使用或打出一张【杀】、【闪】或【酒】。
半重推【缘起】：阶段技，你可以选择一种花色并亮出牌堆顶的一张牌，若颜色相同，你可以将该牌交给一名角色；若花色相同，你可以摸两张牌。

响子 3血 重推 diy：莎墨
【复声】：你可以跳过摸牌阶段，然后依次令其他角色选择令你摸一张牌或令你弃一张牌。若如此做，弃牌阶段开始时，若你手牌数大于体力值，你依次交给令你摸一张牌的角色一张牌;若你手牌数小于体力值，令你弃一张牌的角色依次交给你一张牌。

芙兰朵露
【禁果】：阶段技，你可以选择一项：1. 弃置一张♥手牌并获得一名其他角色的两张牌（不足则全部获得），然后该角色回复1点体力；
2. 获得技能“血呓”（出牌阶段，你可以将一张♥牌当【春雪幻梦】使用。）直到回合结束。
若你发动“禁果”，此阶段结束时，你需展示所有手牌并弃置其中的♥手牌。

爱塔妮缇拉尔瓦
【蝶影】: 弃牌阶段开始时，若你于此回合使用的牌均为同一类别，你可弃置一张牌并对一名未受伤的角色造成1点伤害。

摩多罗隐岐奈
【神呼】: 每当你造成或受到伤害后，你可以与一名其他角色拼点，若你赢，视为你对其使用一张【罔两空界】；若你没赢，其摸一张牌。（删去——然后其于此回合内不是“神呼”的合法目标）

**Comment by MonsterShrubs** [comment]
神小五，观星摸4效果很强，不仅辅助能力强，能给自己摸牌使得自身也不容易成为自身团队突破口，同时自身也因为观星获得高质量的牌而自身进攻力度也不弱，能进入单挑就更不用说了。
所以建议不能给予自己摸牌效果

**Comment by HakureiRin** [comment]
修正：
高丽野阿吽
【狞顾】：出牌阶段，你可以弃置一张“翕”并指定一名其他角色，该角色需选择：交给你一张非基本牌；或失去1点体力。然后其于此回合内不是“狞顾”的合法目标。

神古明地觉
【愈心】：摸牌阶段开始时，你可以放弃摸牌，改为从牌堆顶亮出两张牌并获得之，若这两张牌均为红色，你可以指定一名角色令其选择一项：回复1点体力或摸一张牌。

**Comment by HakureiRin** [comment]
再修正：
高丽野阿吽
【吐纳】：你可以跳过出牌阶段并将任意张点数和不大于13的手牌置于人物牌上，称为“翕”。
【狞顾】：出牌阶段，你可以弃置一张“翕”并指定一名其他角色，该角色需选择：交给你一张非基本牌；或失去1点体力。然后其于此回合内不是“狞顾”的合法目标。

**Comment by MonsterShrubs** [comment]
缘起花色相同是摸三？
神呼那个感觉是要无视合法性
