### ISSUE TITLE
一莎成名2018（下），非东方将修改征集

### ISSUE THREAD

**Issue by HakureiRin** [BeginnerSlob/TouhouTripleSha#266]
已改动——朱鹮、赤座灯里、真红、宫崎和香
强度上没啥问题——黑雪姬、雷电
真的偏弱——赤城、沙耶、阎魔爱、雪风·帕尼托尼
偏强——四糸乃

若有其他需要修改的人物，请提出武将并附上修改方案

**Comment by HakureiRin** [comment]
赤城
彗索（推重）: 当其他角色需要使用或打出【杀】时，你可以打出一张【杀】，视为由其使用或打出。 

沙耶
幻呗: 锁定技。你对**其他**角色、**其他**角色对你使用【杀】时，需连续使用两张【闪】才能抵消。
舞华——君主技。当月势力角色造成伤害后，该角色可以进行一次判定，若结果为黑桃，你可以选择回复1点体力或者**摸2张牌**。

雪风·帕尼托尼
花岚: 一名角色的回合开始时，你可以将至多三张手牌置于牌堆顶，若如此做，此回合弃牌阶段结束时，你摸等同于该角色此阶段弃牌数量的牌。**若其弃牌阶段没有弃牌，你摸一张牌或视为对其使用一张无视距离的【杀】**。

四糸乃
慈雨: 每当一名角色于其出牌阶段内回复体力时，你可选择一项：摸一张牌；或令该角色**摸一张牌**。

**Comment by HakureiRin** [comment]
赤城（替代方案）
彗索: **阶段技，你可以交给其他角色一张杀，当你计算与该角色的距离时，始终为1，直到回合结束。**
苍流: 阶段技。你可以展示你的手牌，若其中没有【杀】，则每当你需要使用或打出一张【杀】时，你可以视为使用或打出了一张【杀】，直到（**删去：你的手牌数变化或**）一名角色死亡。你每回合只能以此法使用或打出三张【杀】。

**Comment by MonsterShrubs** [comment]
阎魔爱
建议加一个能主动掉血并且能和【良坂】有联动的进攻技能
新技能【xx】:你的回合内，当一名其他角色的手牌因弃置进入弃牌堆时，若该角色在你的攻击范围内，你可以失去一点体力，令其获得失去的牌，然后你弃置其等量的牌。

**Comment by MonsterShrubs** [comment]
阎魔爱
加强建议
新技能【xx】:你的回合内，当一名其他角色的手牌因弃置进入弃牌堆时，若该角色在你的攻击范围内，你可以失去一点体力，然后该角色需将等量的手牌（至少一张）替换这些牌。

**Comment by MonsterShrubs** [comment]
赤城建议方案2
1询问太多
