### ISSUE TITLE
入局人员反馈

### ISSUE THREAD

**Issue by shamosha** [BeginnerSlob/TouhouTripleSha#278]
时代在进化，原先四血将每回合一收益（有时候还不到）的环境已经跟不上时代了，需要对给一些将**一点点**的加强；同时，旧时代的角色已经不能激起人们使用的欲望，需要得到更新；并且过于强的角色和破环体验的角色也是存在的，因此利用此贴记录经讨论过的一些角色的修改。

-------------------------大部分参与讨论的人认可的部分-------------------------------

虫子太恶心（虽然胜率不高，但都是最后投降而输，因为太难死）
建议：
蛰隐——当你成为基本牌的目标时，或当你成为锦囊牌的目标时（若你的体力值为1），你可以取消你。每阶段限一次。
改成
蛰隐——当你成为基本牌的目标时，或当你成为锦囊牌的目标时（若你的体力值为1）**，你可以交给使用者/使用者可以交给你一张牌**, 然后取消你。每阶段限一次。
这样其他人在残局也能应对了,而且能够提示队友虫子拥有辅助效果

神小五消耗牌还是比较快，因为观星基本是必发的,所以相当于愈心这个技能不会增加牌差,同时考虑到闭月和攻心的组合已经能抢到桃子,建议把一部分奶量改成过牌
愈心——摸牌阶段开始时，你可以放弃摸牌▶亮出牌堆顶的两张牌，然后获取这些牌，若这些牌均为红色，你可以令一名角色选择一项：1.回复1点体力；2.摸一张牌。
改成
愈心——摸牌阶段开始时，你可以放弃摸牌▶亮出牌堆顶的两张牌，然后获取这些牌，若这些牌均为红色，**你可以令一名角色摸两张牌。**

青蛙子建议加强
（个人觉得祸祟这个技能真的蠢，我还真没见过有人会打出闪的，让人选择这段文本毫无意义。而且本来不打出闪的惩罚已经比较小了，也就过一张牌，居然还能让对面选一个对自己更有利的）
原祸祟——阶段技。你可以弃置一张手牌并选择你的攻击范围内的一名角色▶该角色需打出【闪】，否则你选择一项：1.摸一张牌；2.对其使用【杀】（无距离限制）。
建议改成
**祸祟——当你使用【杀】指定目标/成为【杀】的目标后，你可以令此【杀】使用者交给目标角色一张牌，然后此【杀】不是【闪】的合法目标。**
坤仪——限定技。出牌阶段，你可以将人物牌翻面并选择一名其他角色▶你对该角色造成1点伤害。
天滴不要了

小桶在现在这个时代还只有这种收益(甚至都称不上收益)显然是不符合三血将的模型了,增一点过牌或输出吧
肆暴——你可以将一张装备牌或延时类锦囊牌当【酒】使用,**你使用【酒】时摸一张牌**。
或者
肆暴: **每当其他角色获得你的牌时，你可以视为使用一张无视距离的杀**。

依神紫苑：
对手给出去也不给本人，只会给其队友，这样就只能第一次给出去摸两张牌，后续就摸不到牌了。
所以现在一技能基本就只能发一次摸两张牌，而且会给人有每移动一次摸两张牌的错觉。
建议改成：场上这个标记移动就摸一张牌。
穷乏——锁定技 balabala。**当“贫”标记移动后**，你摸**一**张牌。

依神女苑，散财过于蠢，需要改一改：
原散财——锁定技。当你于摸牌阶段外得到牌后，你将手牌弃置至X张（X为你的手牌上限）。
散财: 锁定技，准备阶段，若你的手牌数大于手牌上限，你需指定一名角色，视为其对你使用了一张【杀】，然后你摸一张牌。

神神妈(还没出新版本就已经要削弱了233)山不会有人用的，远期的收益明显比不过当回合的过牌。湖收益太大,四血将每回合拿2张好牌过于imba。
建议把山和湖改成转换技

梅莉:看你的牌，改你的判，还要用你的牌改，完了还摸1，侮辱性极强,另外和甄姬配合能把牌库摸光
梦违——当一名角色的手牌被展示后，你可以摸一张牌，**每阶段限一次**。
隙境——当一名角色的判定牌生效前，你可以令该角色展示手牌▶你打出其中的一张牌代替之，**每阶段限一次**。

黑兔子，选出来应该就能拿“被无视的可怜人”称号了。也就只有控判定的作用,没什么人理，可以给她加点过牌
开运——当判定牌生效前，你可以观看牌堆顶的两张牌（**删掉弃置一张牌**），然后用其中一张牌代替判定牌，再获取其余的牌

菫子读条太多了，每个回合都有以下步骤：是否发动技能，自己放一张，对面放一张，是否无懈，自己拿一张，对面拿一张。简直是读条地狱。建议在保留机制的前提下稍微改改，同声有一个方案，看着还行。
【幻鉴】：一名角色判定牌或装备区里的牌置入弃牌堆时，你可以将该牌与一张手牌置于你的人物牌上〔称为“鉴”〕。此回合结束时，你可以将一张“鉴”置于牌堆顶。

响子，太容易分光，建议从三血改成四血

布都都几乎必跳出牌阶段，给人的体验很差，建议重做圣贽第一项条件，比如
圣贽——其他角色的回合开始时，你可以令其选择一项：1.**弃置两张花色相同的牌**；2.跳过一个你选择的阶段，然后其对你造成1点伤害。

扇子劝善还行，防御技能发动率真的太低了，一个发动率低，影响不大的技能我觉得不如不加。建议加强,可以根据要加强防御力还是控制能力,进行相应修改
仙罡——当你受到伤害时，你可以判定▶若结果为♣，你防止此伤害；**否则,你可以对当前回合角色发动劝善**

河童，收益不够：
巧工——阶段技。你可以弃置**一张**与场上的一张装备牌颜色相同的牌▶获取此装备牌。

苏我屠自古，闪灵太难发动，只要自己不被集火就发动不了，因此降低它的限制。
闪灵——准备阶段开始时，若你是**攻击范围内**体力值最小的角色，你可以对你的攻击范围内的一名角色造成1点雷属性伤害。

天子真的不适合做主公，首先天子被卖血克死了，其次首回合作为aoe的情况下,反贼一定是要闪的,但忠臣闪或不闪都是亏,也就是说此时这个技能是坑友方的.但是如果不用,像这样的无防御主公还有第二回合吗?我觉得大概率是被一波推了.即使有,那也不如花妈,至少花妈能反推一波,但是天子基本是杀不到有防御力的反贼的.
可以把六震改成:
六震——当你于出牌阶段内使用【杀】指定目标后，你可以选择至少一名不为此【杀】目标的其他角色→当此【杀】因结算完毕而置入弃牌堆前，你对这些角色使用此【杀】（无距离限制）→当此【杀】被抵消时，**目标可以令你**选择一项：1.弃置一张牌；2.**摸一张牌**。每阶段限一次。
这样忠臣的闪能让天子过牌,杀到忠臣也不会很亏了,还能产生一些配合.

-----------------------重做-------------------------------

大妖精：有马术的类似菜刀将已经有太多太多了，而且有点弱，建议推重,方案在争议部分。

文，弱且没有新意，还不能和河童重复，推重了
四血
疾岚——阶段技  你可以选择一名有装备的角色和与其相邻的另一名角色，你视为对前者使用一张【木隐妖岚】，视为对后者使用一张【杀】

九十九姐妹建议重做
她在特定的情况下并不是很弱，比如在某些主公的局中，或者队友的牌被弃置的场合下，收益还是有的。但问题是，谁会选择这么一个有不稳定的配合的角色呢？她的定位不明，选将时总有比她更合适的人，人气低更降低了被选率，所以建议重做。
方案在争议部分.

⑨急冻翻人太强，场上有两张方块装备就能稳定翻人，应该给限制（或者把翻面条件重做）
,方案在争议部分
-----------------------OL----------------------------------
郭嘉可以和ol同步
天妒——当你的判定牌生效后，**你可以将之交给一名角色**。
羽梦——当你受到1点伤害后，你可以摸两张牌，**然后你可以将一张手牌交给一名其他角色,再将一张手牌交给一名其他角色.**
我在ol基础上改了改天妒,被乐拿牌太蠢了.

灯里建议加强
**阶段技**  你可以将一名角色的**牌**(手牌改成牌)弃置至X张（X为其体力值）▶你选择一项：1.你弃置等同于被弃置的牌中非装备牌数量的牌；2.其摸等同于被弃置的牌数量的牌。

亚斯娜可以再加强一点,原先的加强不够，把新老韩当的技能加一起吧
炫刃: 你可以将一张装备牌当【杀】使用或打出，你以此法使用的【杀】无距离限制，**若你以此法使用牌指定目标后，你弃置其一张牌。**
解忧: 当一名角色进入濒死状态时，你可以对当前回合的角色使用一张无视距离且不计入使用限制的【杀】，此【杀】造成伤害时，**（删除你防止此伤害）**，然后若该濒死角色仍处于濒死状态，视为对该濒死角色使用了一张【桃】。

泉此方比较弱
（可以选一个比较强的ol版本，比如
据守：结束阶段，你可以摸一张牌，然后翻面。
解围：当你翻面时，你可以摸一张牌，然后你可以使用一张锦囊牌或装备牌，若如此做，你可以弃置场上与此牌类别相同的一张牌。）

吕蒙可以改成国战版本，因为神吕蒙有攻心，还是不要有重复的技能为好
（
克己：锁定技，弃牌阶段开始时，若你未于出牌阶段内使用过颜色不同的牌或出牌阶段被跳过，你的手牌上限于此回合内+4。
谋断：结束阶段，若你于出牌阶段内使用过四种花色或三种类别的牌，则你可以移动场上的一张牌。）

孙权同步ol:
制衡：出牌阶段限一次，你可以弃置任意张牌，然后摸等量的牌。**若你以此法弃置的牌中包括所有手牌，你多摸一张牌。**
救援：主公技，**其他吴势力角色对其自己使用【桃】时，若其体力值大于你，则该角色可以改为令你回复1点体力，然后其摸一张牌。**

董卓削弱,方案还没定

------------------------------其他-----------------------------------------------
伊十九建议加强,经常一顿操作然后零输出,还把手牌给光了
（可以考虑把导雷的限制去掉，改成：
导雷——阶段技。你可以一张♠牌交给**一名角色**，然后展示其至少一张手牌，若其中有♠牌，你获取其除这些牌外的手牌。若你以此法获得至少三张牌，你失去一点体力。）

------------------------------争议------------------------------------------------
------------------------大妖精----------------
大妖精的推重:
同声的设计
 三血
【织月】：阶段技，你可以观看牌堆顶三张牌，然后将其中1张牌如手牌般使用。
【    】：每当你受到1点伤害时，你可以观看牌堆顶两张牌，可将其中1-2张牌置于牌堆顶或牌堆底，然后摸一张牌。  

感觉这个设计一二技能没有联动,我建议换一个一技能,把这个技能按原织月的思路进行拓展:
三血
【织月】：攻击范围内有你的角色使用杀时，你可以展示牌堆底的一张牌，若此牌为红：你获得此牌并成为此杀的额外目标；若此牌为黑：你可以为此杀指定一个额外目标。
【    】：每当你受到1点伤害时，你可以观看牌堆顶两张牌，可将其中1-2张牌置于牌堆顶或牌堆底，然后摸一张牌。  
这样自己能够多杀,延续了一部分的效果,并且使两个技能互相配合,辅助队友多杀,控制敌人多杀.
-----------------------大狸子-----------------
大狸子的推重:
同声的设计
四血
【戏画】：每当你即将造成伤害时，你可以防止之，然后获得等量的“戏”标记。若你有2枚或以上的“戏”，你拥有“轮钥”。
（轮钥: 当你因其他角色的弃置而失去牌前，或当其他角色得到你的牌前，你可以将移动的牌改为牌堆顶等量的牌。每回合限一次。 ）
【    】：结束阶段开始时，若你于此回合内使用的牌选择过相应目标，你可以弃置至多X枚标记分别对这些角色造成至多X点伤害。若你以此法杀死一名角色，你立即死亡。（X为你已损失的体力值）

我的设计
四血   
①使用一张锦囊时,将此牌放在武将牌上,称为A;你失去一个A后,你于此回合内获得③(一名角色失去体力后,你摸一张牌)
②可以弃置一个A以发动狡兔/反间/蛊惑
这三个技能都有诡计多端的意象,且都有失去体力的效果,我觉得这样非常有契合度
---------------------------九十九---------------------------
九十九的推重: 
改帝的设计
4血
【幻曲】：回合内限一次回合外不限，当你需要使用或打出一张基本牌，你可以将一张手牌作为【谱】扣置在武将牌上。
①若其中有黑桃，视为你使用和打出了一张【杀】，
②若其中有梅花与方块视为你打出了一张【闪】，
③若其中有两张红桃视为你使用了【桃】，
若发动，则弃置全部的【谱】并摸两张牌，并将一张手牌作为【谱】扣置。

还是改帝的设计
九十九 3
【狂筝】：锁定技：当你使用【杀】指定一名角色时，令获得【狂筝】直到其下个回合结束；当你使用的【杀】被一名角色使用的【闪】抵消，此【杀】结算后视为其对你使用了一张【杀】；
【幻曲】：当你被指定为一张【杀】的目标时，你可以为此杀指定一个额外目标，若此【杀】没有造成伤害，你摸两张牌.
----------------------------⑨----------------------------
⑨的推重/修改
改帝的设计
⑨4
【细雪】：目标为你或为你使用的牌的牌生效前，你可以将一张与其花色相同的牌扣置在你的武将牌上称之为【冰】然后令其失效，结算后将这张牌也作为【冰】扣置在你的武将牌上。
【绝零】：准备阶段，若你未获得【3】，且你武将牌上的【冰】大于9张，你扣减一点体力上限且手牌上限恒-1
（【3】：出牌阶段开始时，你需获得你武将牌上的【冰】，直到【冰】不大于9张。）

我的设计
⑨的修改:
寒魄——锁定技。当你受到火属性伤害时，你防止此伤害。你造成的非冰属性伤害视为冰属性伤害.
急冻——锁定技。你的出牌阶段结束时，于此阶段内失去过至少三张牌的角色选择1.将人物牌翻面，然后摸两张牌。2.失去一点体力
氷瀑——限定技。出牌阶段，你可以视为对其他所有角色使用一张杀.此回合结束时,你可以令所有角色翻面.
这样冰伤+失去三张牌的条件1.比最初失去两张容易2.比现在版本困难,
同时⑨在翻别人的同时自己也有可能被翻面,这样就不会产生连续控制了.

同声的设计:
冰魄：锁定技，你的杀均视为冰杀，你的火攻火杀血凤均视为无距离限制的冰杀
氷瀑: 限定技。出牌阶段，你可以令所有其他有牌的角色做出选择：打出一张【闪】，或令你依次弃置其两张牌。

---------------------------------------------------------
灵乌路空（这个真的要加强吗？铁索灭队分分钟的事啊。不过确实这种傻大个的‘许褚’设计不太好，或许半推重比较好？）：
------------------------------私货------------------------------------------------
坂田合欢乃本意是可以重铸装备区的牌（小声），但是鉴于重铸只能手牌，所以希望改成
刃磨——出牌阶段，**你可以弃置一张装备牌▶你摸一张牌**，然后选择一项：1.你的攻击范围于此回合内+1；2.你于此回合的出牌阶段内使用【杀】的次数上限+1。
（其实我觉得直接写“你可以重铸装备区的牌“更符合人物特色）
(被大怪吐槽还是太弱了orz,确实装备很重要,不是随随便便能丢掉的.而且就算是重铸,但是不仅要裸模装备还要裸模杀还是太难了,那就改的激进一点吧:
刃磨——出牌阶段，你可以重铸一张装备牌或弃置一张装备区的牌,▶然后选择一项：1.你的攻击范围和使用【杀】的次数上限于此回合内+2；2.你选择至多两张此阶段进入弃牌堆的基本牌,你获得这些基本牌。)
再写一个魔改版本:
鬼咒——你杀死其他角色后,不执行奖惩,摸两张牌。
刃磨——出牌阶段，你可以弃置一张装备牌▶你的攻击范围于此回合内+1,然后你可以视为使用一张杀,此杀的额定目标数增加x,x为体力值为1的角色的数量.)

建议提高主公这个身份的胜率，削弱反贼, 现在反贼的胜率还是过高了(超过一半).可以把卷子的两个效果交换:
你获得〖梦玄〗〈当你受到1点伤害后，你可以摸一张牌〉。②你成为锦囊牌的目标后，可以令此牌对你无效，然后弃置此【幻想绘卷】。

宫崎和香（马谡）可以加强，比如把殇逝改成
殇逝——当其他角色杀死你时，你可以令**一名角色**弃置你指定的一个区域里的所有牌。
这样就成小透明变成战略武器了。

神cc真的很强，她在控距离/过牌/爆发/偷桃/削减手牌方面都是一把好手，建议至少削掉一个或几个部分。
而且他的二技能,给队友装备还能过一张牌就离谱,光是这个技能,一轮就能多摸两张牌的吧.

建议取消选将时固定的主公位以减少重复对局

**Comment by blackll7** [comment]
大妖精 3
【织月】：一名角色出牌阶段结束时，你可以进行一次判定然后将一张与判定牌花色相同的牌交给该角色，然后你可以获得其余此阶段因弃置而进入弃牌堆的牌中的两张，否则扣减一点体力值.
⑨ 4
【寒月】：阶段技，你可以弃置一张红色牌，然后获得【寒魄】直到你下个出牌阶段开始.
（【寒魄】：锁定技。你的防具牌无效，防止你受到无属性伤害，你受的火属性伤害+1。你造成的非冰属性伤害视为冰属性伤害.）
【急冻】：出牌阶段结束后，若本阶段因弃置而进入弃牌堆的牌不小于三张，你摸一张牌，然后可以对手牌小于你的角色造成一点伤害。

追加一组大妖精和⑨
