### ISSUE TITLE
小野寺小咲-轮钥x莉西娅-燕语

### ISSUE THREAD

**Issue by Leoongithub** [BeginnerSlob/TouhouTripleSha#36]
当小野寺的杀或闪因弃置或打出，即将被莉西娅获得时，结算不正确（小野寺仍持有弃置或打出的牌，莉西娅摸一张牌）。

**Comment by Leoongithub** [comment]
1.莉西娅 燕语 可获取 小野寺小咲 使用的牌，但获取 小野寺小咲 弃置或打出的牌时，会以牌堆顶的代替。
2.莉西娅 无法获得自己的牌。

**Comment by BeginnerSlob** [comment]
认真看了一下，似乎不是BUG
