### ISSUE TITLE
小型剧场

### ISSUE THREAD

**Issue by Leoongithub** [BeginnerSlob/TouhouTripleSha#45]
各种游戏开始时的技能无法正确发动：
神博丽灵梦-巫道
寅丸星-初辉
土御门夏目-七曜
嘉依卡-元姬
木之本樱-幻身
阿斯特莱雅-拙火

神将没有选择势力。

**Comment by Leoongithub** [comment]
元姬、初辉、拙火仍存在bug：如在小剧场选择其中两人，然后开始游戏（必须开两个客户端加进去，单机启动无法复现）。

**Comment by BeginnerSlob** [comment]
mark和势力都能手动添加，懒得debug了
