### ISSUE TITLE
神天子的各种bug

### ISSUE THREAD

**Issue by shamosha** [BeginnerSlob/TouhouTripleSha#69]
如意：桃 无中 五谷 百鬼 血凤(可能还有其他牌)可能会导致系统崩溃  
流払：牌交给其他角色后，此牌不会因弃置或使用而进入弃牌堆

已修复部分
普救：技能按键灰色
破荒：必须发动 
断龙：如果发动天宝弃置又获得，则不会触发

**Comment by BeginnerSlob** [comment]
流払 这是什么BUG，还能重现么
