### ISSUE TITLE
幻境与同类合法性问题

### ISSUE THREAD

**Issue by shamosha** [BeginnerSlob/TouhouTripleSha#74]
幻境(和一些需要cost的技能)使用牌时不检测合法性，以下是所有可能出现的状况（待补充）

通用
目标死亡
使用者死亡

杀
目标被调虎
距离变动
火鼠裘
诸葛空城
穹禁恋
次数限制

桃
目标体力等于体力上限
神天子摧骨

酒
次数限制

铁索
火鼠裘

借刀
武器牌
攻击范围内没有合法目标

顺手
目标区域没有牌
距离变动

拆
目标区域没有牌

火凤
火鼠裘

幽瞳
目标没有手牌

火攻
目标没有手牌

**Comment by BeginnerSlob** [comment]
上面这些测试过了吗？

**Comment by shamosha** [comment]
测了杀桃酒借刀拆火攻，其他的感觉原理差不多没测

**Comment by BeginnerSlob** [comment]
不会崩就关了
