### ISSUE TITLE
流払引起程序崩溃

### ISSUE THREAD

**Issue by Misaka2623** [BeginnerSlob/TouhouTripleSha#78]
神比那名居天子在上家使用荒波暴流被指定目标时发动流払，先选择选项2，再选择选项1。在荒波暴流结算结束后流払2被触发，然后程序崩溃
![image](https://cloud.githubusercontent.com/assets/7156817/25033140/ad6d83f0-208f-11e7-99df-6607189ebbb0.png)

**Comment by BeginnerSlob** [comment]
没法重现，待定
