### ISSUE TITLE
一些建议？

### ISSUE THREAD

**Issue by bokuwaahoya** [BeginnerSlob/TouhouTripleSha#82]
1.开放单机作弊（单机点将）
       小场景调用还是有点麻烦的
2.服务器统计
3.自动保存录像
4.无懈系统
     无懈撞车惨案时有发生
5.自动检测连接状态
     现在靠的是手动检测（随便发一条聊天信息）

**Comment by BeginnerSlob** [comment]
1.在Config.ini里面加一行EnableTest=true
2.3.不着急，
4.已经被其他issue谈及（#18）
5.不着急

**Comment by Misaka2623** [comment]
6. 游戏内悬浮描述中花色太小，经常分不清黑桃和梅花（17"显示器 1920x1080）

**Comment by BeginnerSlob** [comment]
5条都解决了，@Misaka2623 6这条你可以自己更换图片，有好的图片这里也可以加
