### ISSUE TITLE
关于主页的建议

### ISSUE THREAD

**Issue by Misaka2623** [BeginnerSlob/TouhouTripleSha#85]
1. 表格宽度应该要弄成自适应窗口？

**Comment by Misaka2623** [comment]
想要当窗口宽度大于现在这个表格宽度的时候表格大小不变，但是当窗口宽度小于这个表格宽度的时候表格自适应窗口宽度
然而不知道怎么样读取当前窗口大小

**Comment by Htgs** [comment]
是网页的表格吗，可以用样式修改也可以用js修改啊

**Comment by Leucothea** [comment]
这个先不改了 搁置吧 excel也没这么麻烦
