### ISSUE TITLE
WIKI与卡图的区别

### ISSUE THREAD

**Issue by Misaka2623** [BeginnerSlob/TouhouTripleSha#87]
- [x] 晓美焰 - 华岸 | 使用兵粮寸断 | 将兵粮寸断置于判定区
- [x] 朱鹭子 - 授卷 | 技能效果几乎不一样
- [x] 梅莉 - 隙境 | 弃置+获得（ps: 御坂美琴那是用的替换） | 替换
- [x] 冴月麟 - 星屑 | 获得；标记 | 获得并使用
- [x] 泠仙 - 羽帛 | 弃置手牌是代价 | 弃置手牌是效果？
- [x] 本居小铃 - 诈诱 | 杀的目标为本居小铃 | 疑似在杀曹操，曹操护驾的情况下，也能发动
- [x] 神绮 - 妄道 | |有歧义，“对你使用一张花色相同的无视距离的杀”可理解为必须使用“无视距离的杀”，而现阶段牌堆里没有哪张杀可以无视距离
- [x] 天照 - 四象 | | 然后然后；选项4的“然后弃置一张牌”有“天照弃置一张牌”的歧义
- [x] 三千院凪 - 唤卫 | 其他花势力角色打出闪 | 其他花势力角色使用或打出闪
- [x] 秋庭里香 - 清俭 | 同时交给一名角色 | 似乎可以一张一张给
- [x] 葵喜美 - 裸衣 |标记
- [x] 艾丽 - 灵战 | 标记
- [x] 弓塚五月 - 桔界 | 可以对距离为2的角色使用 | 可以对距离2以内的角色使用
- [x] 泉此方 - 宅魂 | 标记
- [x] 泉此方 - 佛脚 | 将装备区里的一张牌当无懈可击 | 将装备区里的一张装备牌当无懈可击
- [x] 丽夏麻绪 - 幻舞 | 无限定时机（顺手牵羊默认出牌阶段才能使用） | 限制出牌阶段才能将“隐”当顺手牵羊使用
- [x] 赤座灯里 - 飘念 | | 原意是双方都不处于连环状态时才能发动吗？
- [x] 桂言叶 - 崩殇 | 手牌上限+X（殇的数量） | 手牌上限+X（人物牌上牌的数量）
- [x] 黑瞳 - 八狩 | 弃置一张非基本牌 | 弃置一张装备牌并令你摸一张牌
- [x] 梅娅- 狩魇 | 弃置装备牌→人物牌翻面 | 人物牌翻面→弃置装备牌
- [x] 司波深雪 - 雪涟 | 来源死亡无法回血 | 来源死亡回血
- [x] 坂井和奏 - 弧音 | 标记；移出游戏的牌命名；获得所有“律” | 获得所有人物牌上的牌
- [x] 蔻蔻 - 归心 | 获得牌是代价 | 获得牌是效果？
- [x] 长门有希 - 忍枷 | “桎”标记 | “天枷”标记
- [x] 菲娅 - 方圣 | 可以交给自己？ | 交给其他角色
- [x] 若狭悠里 - 巡御 | 灵卫 | 慧払

**Comment by Leucothea** [comment]
All Done
