### ISSUE TITLE
一些需要虫娘改动的东西

### ISSUE THREAD

**Issue by Leucothea** [BeginnerSlob/TouhouTripleSha#88]
- [x] 1.主界面字体==>方正古隶GBK(找不到可以问我要这个字体)
- [x] 2. 字体外发光颜色从黄色改成#f4f2f8
- [x] 3. "关于"条目里 添加 wiki和主页 网址链接
- [x] 4. 游戏牌表示框右移一些，尽量居中 (就是屯田什么的)
- [x] 5. 模式一览按钮改为"资料收录"(叫官方主页没人会点进去看的)

**Comment by BeginnerSlob** [comment]
all over
